name: flutter_audio_scenes
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  backstreets_widgets: ^0.25.0
  cupertino_icons: ^1.0.8
  dart_style: ^3.0.1
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.32.1
  flutter_soloud: ^2.1.7
  json_annotation: ^4.9.0
  path: ^1.9.1
  pub_semver: ^2.1.5
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
    - sounds/
